### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by ubuntudroid** [evfool/language-vala#2]
Atom warns when running the plugin in version 0.1.0:

> Store package settings files in the `settings/` directory instead of `scoped-properties/`
> 
> ```
> Package.loadSettings (/usr/share/atom/resources/app.asar/src/package.js:552:9)
> <unknown> (/usr/share/atom/resources/app.asar/src/package.js:168:43)
> Package.measure (/usr/share/atom/resources/app.asar/src/package.js:147:15)
> Package.load (/usr/share/atom/resources/app.asar/src/package.js:161:12)
> ```

**Comment by evfool** [comment]
Thanks for the PR, merged into master.

**Comment by fradelg** [comment]
Please, make `apm publish minor` to publish the update in the Atom package repository

Thanks!

**Comment by evfool** [comment]
Minor update published, feel free to test it. Thanks for your help.

**Comment by fradelg** [comment]
Thanks! I've received the update and now the package is adapted to Atom 1.0 API :+1:
